repos:
  - repo: local
    hooks:
      - id: dart-format
        name: Dart Format
        entry: dart format .
        language: system
        types: [dart]

      - id: flutter-analyze
        name: Flutter Analyze
        entry: flutter analyze
        language: system
        types: [dart]
